version: '3'
services:
#  jira:
#    image: cptactionhank/atlassian-jira:latest
#    restart: always
#    links:
#      - database
#    volumes:
#      - jira-data:/var/atlassian/jira

  confluence:
    image: cptactionhank/atlassian-confluence:latest
    restart: always
    ports:
      - "8090:8090"
    links:
      - database
    volumes:
      - confluence-data:/var/atlassian/confluence

  database:
    image: postgres:9.4
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./scripts/setup-confluence-db.sh:/docker-entrypoint-initdb.d/setup-confluence-db.sh
      - ./tmp:/tmp/dumps # import backups
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
#      - jira
      - confluence
    volumes:
    - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
    - DOMAIN
volumes:
#  jira-data:
  confluence-data:
  database-data:
